# Generated by Django 3.2.5 on 2022-05-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coverImage',
            field=models.ImageField(default=None, upload_to='images/products'),
            preserve_default=False,
        ),
    ]
